"use client";

import { CheckCircle, UserPlus, BarChart3, ArrowUpRight, Repeat, Link2 } from "lucide-react";

export default function HowItWorksSection() {
 const steps = [
  {
    icon: <CheckCircle className="h-6 w-6 text-black" />,
    title: "Create Campaign",
    desc: "Set up your campaign with products, commission rates, and tracking parameters.",
  },
  {
    icon: <UserPlus className="h-6 w-6 text-black" />,
    title: "Invite Creators",
    desc: "Enter creator emails to invite them to your campaign.",
  },
  {
    icon: <Link2 className="h-6 w-6 text-black" />,
    title: "Creators Generate Referral Links",
    desc: "Creators create multiple referral links for each social media platform themselves.",
  },
  {
    icon: <BarChart3 className="h-6 w-6 text-black" />,
    title: "Track Sales & Clicks",
    desc: "Track every sale and click generated by creator referral links for your products and campaign.",
  },
  {
    icon: <ArrowUpRight className="h-6 w-6 text-black" />,
    title: "Analyze & Scale",
    desc: "View dashboards with campaign performance and use insights to optimize and grow.",
  },
];


  return (
    <section id="how-it-works" className="lg:py-32">
      <div className="mx-auto max-w-7xl px-6">
        {/* Header */}
        <div className="text-center mb-20">
          <span className="bg-white inline-flex items-center rounded-full border px-4 py-1.5 text-sm font-medium">
            How It Works
          </span>

          <h2 className="mt-6 text-4xl md:text-5xl font-semibold tracking-tight">
            Get started with
            <span className="text-primary"> creator marketing</span>
          </h2>

          <p className="mt-4 text-lg text-muted-foreground">
            Follow these five steps to launch, track, and scale your campaigns efficiently.
          </p>
        </div>

        {/* Bento Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left Big Card */}
          <div className="lg:col-span-7 rounded-3xl border bg-card p-10 relative overflow-hidden">
            <div className="absolute inset-0 bg-linear-to-br from-primary/5 to-transparent" />
            <div className="relative z-10 space-y-8">
              {steps.slice(0, 3).map((step, idx) => (
                <div key={idx} className="flex items-start gap-4">
                  <div className="flex-none h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center">
                    {step.icon}
                  </div>
                  <div>
                    <h4 className="text-xl font-semibold mb-1">{step.title}</h4>
                    <p className="text-sm text-muted-foreground">{step.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Right Stack */}
          <div className="lg:col-span-5 grid gap-6">
            {steps.slice(3).map((step, idx) => (
              <div
                key={idx}
                className="rounded-3xl border bg-card p-8 relative overflow-hidden hover:shadow-lg transition-all"
              >
                <div className="absolute inset-0 bg-linear-to-br from-primary/5 to-transparent" />
                <div className="relative z-10">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center">
                      {step.icon}
                    </div>
                    <h4 className="font-semibold">{step.title}</h4>
                  </div>
                  <p className="text-sm text-muted-foreground">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>

        </div>
      </div>
    </section>
  );
}
